### PR TITLE
Fixed #5 ("Production build fails with aot enabled")

### LINKED ISSUE #5: Production build (with "aot" enabled) fails when library is imported as a package
Steps to reproduce:
* Generate a new Angular app
* Import the package the following way:
`import {NguiInviewModule} from '@ngui/common';`
* Try to build the app:
`ng build --prod`

Result:
`ERROR in : Unexpected value 'NguiInviewModule in C:/<REDACTED>/node_modules/@ngui/common/modules/dist/inview/src/ngui-inview.module.d.ts' imported by the module 'SharedModule in C:/<REDACTED>/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.`

Production build works fine when importing the module directly like you do in your demo app. The issue only occurs when the module is imported from a package.

Following bug reports might be related to the issue:
[ng-packagr#355](https://github.com/dherges/ng-packagr/issues/355)
[ng-packagr#195](https://github.com/dherges/ng-packagr/issues/195)

EDIT:
[Angular issue](https://github.com/angular/angular/issues/23713)
[Angular Pull Request](https://github.com/angular/angular/pull/22856)

### PR DESCRIPTION
**Pull request by hakimio**
* Split the project into two main workspaces: the library (projects/ngui-inview) and the test app (src).
* Updated the test app to Angular 6.1.
* Some minor fixes to make static analysis happy.

* All unit and acceptance tests still succeed.
* Demo app also still works as expected.

If you want any changes, let me know.

### CODE REVIEW

**Comment by hakimio** [comment]
@allenhwkim Can you help me with a couple of things:
* Do you have any idea why unit tests work fine locally but fail in Travis CI?
* Can you fix the link to Demo project. I thought I knew where it should point to but apparently I didn't?

**Comment by allenhwkim** [comment]
@hakimio I will look into it, but later. Currently busy doing bill-paying jobs :)

**Comment by hakimio** [comment]
Sure, no problem.
Anyway, demo app link seems to be failing because I somehow managed to forget to commit production demo app build.
If you could just run "npm run build:app" and then commit it, would be great.
The other issue can wait.

**Comment by hakimio** [comment]
Also, it would be great if you could publish a new version.

**Comment by allenhwkim** [comment]
Could not build because the test is failing. :(

```
ngui-common$ (master) npm test

> @ngui/common-app@0.3.2 test /Users/allen.kim/github/ngui-common
> npm run test:unit && npm run test:acceptance


> @ngui/common-app@0.3.2 test:unit /Users/allen.kim/github/ngui-common
> jest --coverage=true

 FAIL  projects/ngui-common/src/lib/ngui-list/src/ngui-list-item.directive.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-list/src/ngui-autocomplete.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-inview/src/ngui-inview.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-list/src/ngui-virtual-list.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-list/src/ngui-inview-page.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-utils/src/dynamic-component.service.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-inview/src/ngui-inview.directive.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-utils/src/konsole.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-list/src/ngui-list.directive.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-utils/src/ngui-highlight.pipe.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  projects/ngui-common/src/lib/ngui-utils/src/file-event.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    /Users/allen.kim/github/ngui-common/test/jest-setup.ts:14
    import 'jest-preset-angular';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

Running coverage on untested files...Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-list/src/ngui-autocomplete.component.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (20:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (20:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-list/src/ngui-inview-page.component.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (10:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (10:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-list/src/ngui-list-item.directive.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (13:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (13:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-utils/src/dynamic-component.service.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (38:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (38:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-utils/src/ngui-highlight.pipe.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (7:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (7:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-list/src/ngui-virtual-list.component.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (10:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (10:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-list/src/ngui-list.directive.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (10:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (10:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-inview/src/ngui-inview.directive.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (13:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (13:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
Failed to collect coverage from /Users/allen.kim/github/ngui-common/projects/ngui-common/src/lib/ngui-inview/src/ngui-inview.component.ts
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (13:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (13:0)
    at Parser.pp$5.raise (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/allen.kim/github/ngui-common/node_modules/babylon/lib/index.js:7305:37)
    at Instrumenter.instrumentSync (/Users/allen.kim/github/ngui-common/node_modules/istanbul-lib-instrument/dist/instrumenter.js:123:31)
    at exports.default (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/generate_empty_coverage.js:32:18)
    at Object.worker (/Users/allen.kim/github/ngui-common/node_modules/jest/node_modules/jest-cli/build/reporters/coverage_worker.js:53:73)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Jest: Coverage data for global was not found.
Test Suites: 11 failed, 11 total
Tests:       0 total
Snapshots:   0 total
Time:        4.834s
Ran all test suites.
jest-html-reporter >> Report generated (/Users/allen.kim/github/ngui-common/test-report.html)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ngui/common-app@0.3.2 test:unit: `jest --coverage=true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ngui/common-app@0.3.2 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/allen.kim/.npm/_logs/2018-08-01T02_14_48_843Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by hakimio** [comment]
I tested by doing clean install from my branch.
Just doing "npm install" and then running "npm run test:unit" works well for me. 
Maybe some environment issue? Whant version of node and npm do you have? For me:
Node: 10.1.0
npm: 6.2.0

Anyway, I'll try to see if I can reproduce the issue on my end.

**Comment by hakimio** [comment]
Some kind of environment issue which I can't figure out. Tests run fine on Windows machine but fail with above error on Linux even when using same npm and node. I am not an expert in jest, so I am not really sure how to solve this right now, but I'll see if I can find anything.

Following seem to be related issue reports:
https://github.com/thymikee/jest-preset-angular/issues/64
https://github.com/thymikee/jest-preset-angular/issues/66

**Comment by hakimio** [comment]
Checked "jest --debug" and the only real difference I can see is that on windows it reports version "23.2.0" and on linux it says "23.4.2".

@sharikovvladislav Could you help us with this "jest-preset-angular" issue?

**Pull request merged**
