### PR TITLE
Angular 6 & RxJS 6.2.1

### PR DESCRIPTION
**Pull request by hakimio**
* The module builds successfully
* Tests run successfully
* Demo app seems to be working fine as well

* As a small bonus I've also fixed some static analysis warnings

### CODE REVIEW

**Comment by hakimio** [comment]
@allenhwkim Can you publish new version to npm?

**Comment by allenhwkim** [comment]
@hakimio thanks for finding this module. published as 0.3.0
I had to change this
`ng build --prod --base-href=.`
 to 
`ng build --base-href=.`

**Comment by hakimio** [comment]
@allenhwkim In your "angular.json" file you have to add a new "production" configuration on line 28.
It should look like the following:
```json
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
```

Then production build works fine.

**Comment by hakimio** [comment]
Also, just a couple small things:
* When I was searching for Angular virtual scrolling library I couldn't find your module. Could add a couple more tags: "virtual-scroll", "lazy-rendering", etc
* Since now the library is Angular 6+, it might be a good idea to update the README and repository description.

**Comment by allenhwkim** [comment]
@hakimio can you make another PR with those change too?

**Comment by hakimio** [comment]
Sure, I'll do that tomorrow.

**Pull request merged**
