### PR TITLE
Jest test fix for linux

### PR DESCRIPTION
**Pull request by hakimio**
Hopefully this fixes jest tests on linux.
Thanks @sharikovvladislav .

### CODE REVIEW

**Comment by hakimio** [comment]
@allenhwkim Travis CI seems to be happy now :)

**Comment by allenhwkim** [comment]
Changed back package name `@ngui/common` from `@ngui/common-app` to publish properly

It's published as version 0.4.0

**Comment by hakimio** [comment]
@allenhwkim
* There is another "package.json" file in projects/ngui-common folder which gets copied to dist folder when you build the library/module. Can't you use that one to publish? I wanted to separate library package.json and demo app package.json. Take a look at "package.json files" section in [this tutorial](https://blog.angularindepth.com/creating-a-library-in-angular-6-part-2-6e2bc1e14121#822e).
* Can you build the demo app and make sure "Demo" link works?
* Do acceptance tests work for you on linux?

**Comment by hakimio** [comment]
Just checked the new package. I really don't think you should include the test app, documentation, tests, test results, etc in there. Imho, it should only be the library package which you can generate now by simply running `npm run package`. The resulting tgz file will be in dist/ngui-common folder.

**Comment by allenhwkim** [comment]
I got it. Can you make another PR with .npmignore?

**Comment by hakimio** [comment]
Do you really need it? Can't you just run `npm run package` and publish the tgz file generated with it? 
If you actually want to include some extra stuff besides the library itself, maybe you should decide which files belong in there because for me just the library seems to be enough.

**Comment by hakimio** [comment]
BTW, you might want to fix "homepage" and "bugs" urls in app and library package.json files. They are pointing to the wrong github page.

**Comment by hakimio** [comment]
Just to make sure we understand each other: 
* I have introduced ["pack" and "package" scripts](https://github.com/allenhwkim/ngui-common/blob/master/package.json#L20) in the root package.json file based on the tutorial I have linked above.
* The "package" script does the following:
```
# Builds the library
ng build --prod ngui-common
# Creates .tgz archive inside dist/ngui-common
cd dist/ngui-common
npm pack
```
* You should be able to simply publish the resulting file

**Comment by allenhwkim** [comment]
@hakimio I will give you publish permission, so that you can do.
Can you provide your npm user?

**Comment by hakimio** [comment]
@allenhwkim It's the same: hakimio

**Comment by allenhwkim** [comment]
You are now a maintainer of `@ngui/common`
image

Please LMK if you have any issue of publishing it.

**Comment by hakimio** [comment]
Thanks. Can you see why Demo app link still doesn't work?

**Comment by hakimio** [comment]
Also, if you are willing to give permission to publish packages, maybe you could give me write access to this repository? Or do you still want to manually approve all my pull requests for some time?

**Comment by allenhwkim** [comment]
image
You are added as a collaborator.

**Comment by hakimio** [comment]
@allenhwkim I still don't have permission to edit repository description (one line description on top of the page) which right now says: "Angular 5 Inview, List, Virtual List, Auto**cmp**lete, etc..."
Can you change it to: "Angular 6 Virtual Scroll, Lazy Rendering, Virtual List, Autocomplete, etc"
Also the tags on top could be "angular", "virtual scroll", "lazy rendering".

**Comment by allenhwkim** [comment]
I think that part is only modifiable by the owner. I changed as you mentioned.
image

**Comment by hakimio** [comment]
Looks good. Do you think we should also link your article published on medium in the README?

**Comment by allenhwkim** [comment]
@hakimio why not? I gave you full permission, and you can make any change and make PR.

**Comment by hakimio** [comment]
@allenhwkim Can you update "ngxui/common" readme to say that it's deprecated repository and link to "allenhwkim/ngui-common"?

**Comment by allenhwkim** [comment]
Can I delete `ngxui/common`?

**Comment by hakimio** [comment]
Sure, you can do that.

**Comment by sharikovvladislav** [comment]
@hakimio wait what? :) why thanks to me :) ???

**Comment by hakimio** [comment]
@sharikovvladislav I found out how to fix this based on one of your PRs/commits. Don't remember which one now.

**Comment by hakimio** [comment]
@sharikovvladislav it was actually [this PR](https://github.com/kidd3/SL/pull/4).

**Comment by sharikovvladislav** [comment]
Okay ! Very cool! :)

**Pull request merged**
